--- #YAML:1.0
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: Module::Build version 0.11
license: perl
name: Test-Signature
recommends: {}
requires:
  Test::Builder: 0.17
  perl: 5.6.0
version: 1.02
