--- #YAML:1.0
distribution_type: module
name: Test-Signature
date: 1 Aug 2003
author: SPOON
version: 1.05
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  File::Find::Rule: 0.11
  Module::Signature: 0.28
  Test::Pod: 0.95
requires:
  Test::Builder: 0.17

private:
  directory:
    - t

provides:
  Test::Signature:
    file: lib/Test/Signature.pm
    version: 1.05

dynamic_config: 0
generated_by: docmaker version 0.91
